version: 2

jobs:
  11-bionic:
    docker:
      - image: vapor/swift:5.1-bionic
      - image: circleci/postgres:11
        name: psql
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - checkout
      - run: swift build
      - run: swift test
  10-bionic:
    docker:
      - image: vapor/swift:5.1-bionic
      - image: circleci/postgres:10
        name: psql
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - checkout
      - run: swift build
      - run: swift test
  9-bionic:
    docker:
      - image: vapor/swift:5.1-bionic
      - image: circleci/postgres:9
        name: psql
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - checkout
      - run: swift build
      - run: swift test
  bionic-release:
    docker:
      - image: vapor/swift:5.1-bionic
    steps:
      - checkout
      - run: swift build -c release
  linux-performance:
    docker:
      - image: vapor/swift:5.1-bionic
      - image: circleci/postgres:11
        name: psql
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - checkout
      - run: swift test -c release
workflows:
  version: 2
  tests:
    jobs:
      - 11-bionic
      - 10-bionic
      # - 9-bionic
      - bionic-release
