version: 2

jobs:
  macos:
    macos:
      xcode: "9.2"
    steps:
      - checkout
      - run: swift build
      - run: swift test
  linux-10:
    docker:
      - image: codevapor/swift:4.1
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
  linux-9:
    docker:
      - image: codevapor/swift:4.1
      - image: circleci/postgres:9
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
  linux-release:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - checkout
      - run: 
          name: Compile code with optimizations
          command: swift build -c release
workflows:
  version: 2
  tests:
    jobs:
      - linux-10
      - linux-9
      - linux-release
      # - macos
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master       
    jobs:
      - linux
      # - macos
      
