#if !canImport(ObjectiveC)
import XCTest

extension FluentPostgresDriverTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FluentPostgresDriverTests = [
        ("testAggregate", testAggregate),
        ("testAll", testAll),
        ("testArray", testArray),
        ("testBatch", testBatch),
        ("testBlob", testBlob),
        ("testChildren", testChildren),
        ("testChunk", testChunk),
        ("testCRUD", testCRUD),
        ("testCustomJSON", testCustomJSON),
        ("testDatabaseError", testDatabaseError),
        ("testEagerLoad", testEagerLoad),
        ("testEnum", testEnum),
        ("testFilter", testFilter),
        ("testGroup", testGroup),
        ("testID", testID),
        ("testJoin", testJoin),
        ("testMiddleware", testMiddleware),
        ("testMigrator", testMigrator),
        ("testModel", testModel),
        ("testOptionalParent", testOptionalParent),
        ("testPagination", testPagination),
        ("testParent", testParent),
        ("testPerformance", testPerformance),
        ("testRange", testRange),
        ("testSaveModelWithBool", testSaveModelWithBool),
        ("testSet", testSet),
        ("testSiblings", testSiblings),
        ("testSoftDelete", testSoftDelete),
        ("testSort", testSort),
        ("testTimestamp", testTimestamp),
        ("testTransaction", testTransaction),
        ("testUnique", testUnique),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FluentPostgresDriverTests.__allTests__FluentPostgresDriverTests),
    ]
}
#endif
