#if !canImport(ObjectiveC)
import XCTest

extension FluentPostgresDriverTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FluentPostgresDriverTests = [
        ("testAggregates", testAggregates),
        ("testAll", testAll),
        ("testAsyncCreate", testAsyncCreate),
        ("testBatchCreate", testBatchCreate),
        ("testBatchUpdate", testBatchUpdate),
        ("testChunkedFetch", testChunkedFetch),
        ("testCreate", testCreate),
        ("testDelete", testDelete),
        ("testEagerLoadChildren", testEagerLoadChildren),
        ("testEagerLoadChildrenJSON", testEagerLoadChildrenJSON),
        ("testEagerLoadParent", testEagerLoadParent),
        ("testEagerLoadParentJoin", testEagerLoadParentJoin),
        ("testEagerLoadParentJSON", testEagerLoadParentJSON),
        ("testIdentifierGeneration", testIdentifierGeneration),
        ("testJoin", testJoin),
        ("testLifecycleHooks", testLifecycleHooks),
        ("testMigrator", testMigrator),
        ("testMigratorError", testMigratorError),
        ("testNestedModel", testNestedModel),
        ("testNullifyField", testNullifyField),
        ("testRead", testRead),
        ("testSaveModelWithBool", testSaveModelWithBool),
        ("testSoftDelete", testSoftDelete),
        ("testSort", testSort),
        ("testTimestampable", testTimestampable),
        ("testUniqueFields", testUniqueFields),
        ("testUpdate", testUpdate),
        ("testUUIDModel", testUUIDModel),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FluentPostgresDriverTests.__allTests__FluentPostgresDriverTests),
    ]
}
#endif
