import Service

/// Adds Fluent PostgreSQL's services to your project.
public final class FluentPostgreSQLProvider: Provider {
    /// See `Provider.repositoryName`
    public static let repositoryName = "fluent-postgresql"

    /// Creates a new `FluentPostgreSQLProvider`
    ///
    /// - enableIdentityColumns: If true, `GENERATED BY DEFAULT AS IDENTITY` will be used.
    ///                          `true` by default.
    public init(enableIdentityColumns: Bool? = nil) {
        if let enableIdentityColumns = enableIdentityColumns {
            _globalEnableIdentityColumns = enableIdentityColumns
        }
    }

    /// See `Provider.register(_:)`
    public func register(_ services: inout Services) throws {
        try services.register(FluentProvider())
        try services.register(PostgreSQLProvider())
    }

    /// See `Provider.boot(_:)`
    public func boot(_ worker: Container) throws { }
}

/// Enabled by default
internal var _globalEnableIdentityColumns: Bool = true
