import Async
import Foundation

/// Adds ability to create, update, and delete schemas using a `PostgreSQLDatabase`.
extension PostgreSQLDatabase: SchemaSupporting {
    /// See `SchemaSupporting.dataType`
    public static func dataType(for field: SchemaField<PostgreSQLDatabase>) -> String {
        var string: String
        switch field.type.type {
        case .bool: string = "BOOLEAN"
        case .bytea: string = "BYTEA"
        case .char: string = "CHAR"
        case .int8: string = "BIGINT"
        case .int2: string = "SMALLINT"
        case .int4, .oid, .regproc: string = "INTEGER"
        case .text, .name: string = "TEXT"
        case .point: string = "POINT"
        case .float4: string = "REAL"
        case .float8: string = "DOUBLE PRECISION"
        case ._aclitem: string = "_aclitem"
        case .bpchar: string = "BPCHAR"
        case .varchar: string = "VARCHAR"
        case .date: string = "DATE"
        case .time: string = "TIME"
        case .timestamp: string = "TIMESTAMP"
        case .numeric: string = "NUMERIC"
        case .void: string = "VOID"
        case .uuid: string = "UUID"
        case .jsonb: string = "JSONB"
        case .json: string = "JSON"
        case .pg_node_tree: string = "pg_node_tree"
        default: string = "VOID" // FIXME: better error?
        }

        if field.type.size >= 0 {
            string += "(\(field.type.size))"
        }

        if field.isIdentifier {
            switch field.type.type {
            case .int8, .int4, .int2: string += " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            default: string += " PRIMARY KEY"
            }
        } else if !field.isOptional {
            string += " NOT NULL"
        }

        return string
    }

    /// See `SchemaSupporting.fieldType`
    public static func fieldType(for type: Any.Type) throws -> PostgreSQLColumn {
        if let representable = type as? PostgreSQLColumnStaticRepresentable.Type {
            return representable.postgreSQLColumn
        } else {
            throw PostgreSQLError(
                identifier: "fieldType",
                reason: "No PostgreSQL column type known for \(type).",
                suggestedFixes: [
                    "Conform \(type) to `PostgreSQLColumnStaticRepresentable` to specify field type or implement a custom migration.",
                    "Specify the `PostgreSQLColumn` manually using the schema builder in a migration."
                ]
            )
        }
    }

    /// See `SchemaSupporting.execute`
    public static func execute(schema: DatabaseSchema<PostgreSQLDatabase>, on connection: PostgreSQLConnection) -> Future<Void> {
        do {
            var schemaQuery = schema.makeSchemaQuery(dataTypeFactory: dataType)
            schema.applyReferences(to: &schemaQuery)
            let sqlString = PostgreSQLSQLSerializer().serialize(schema: schemaQuery)
            return try connection.query(sqlString).map(to: Void.self) { rows in
                assert(rows.count == 0)
            }
        } catch {
            return Future(error: error)
        }
    }
}
